### ISSUE TITLE
Not working on latest version of Adapt framework

### ISSUE THREAD

**Issue by imjosecampos** [adamlaird/adapt-menu-singlePageCourse#8]
I tried it with the latest version and it seems that it tries to route but then get re-routed to the menu, the only solution I found was to change the URL(ignore backbone) when the page loads.

**Comment by andrewhosgood** [comment]
You probably don't need this any more, but you can add this to line 9:

`Adapt.router.set( '_canNavigate', true, { pluginName: 'adapt' } );`

**Comment by imjosecampos** [comment]
Thanks for your response!

**Comment by adamlaird** [comment]
added as suggested. Thanks
