### ISSUE TITLE
Issues uploading into 2.0

### ISSUE THREAD

**Issue by petchie** [adamlaird/adapt-menu-singlePageCourse#9]
Hi,

I'm having issues uploading the plug into my server side Adapt Authoring tool. I'm receiving this following message upon upload. 

"Plugin upload failed
Error: Unrecognized plugin type for package adapt-menu-singlePageCourse"

thoughts?

Thanks in advance
Nick

**Comment by RickVanLouis** [comment]
Hey guys, hey petchie,

i got the same Problem. I'm pretty sure that most of the plugins are made for the Framework and not for the Authoring Tool. But maybe there is a workaround?

Thanks in advance
Manu

**Comment by adamlaird** [comment]
Yes this was made for the framework as use that rather than the authoring tool.
